# Production docker-compose with secrets and monitoring

services:
  roblox-garden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roblox-garden-prod
    restart: unless-stopped
    
    # Use secrets for sensitive data
    secrets:
      - telegram_bot_token
      - updates_channel_id
      - full_channel_id
    
    environment:
      # WebSocket settings
      - WS_URL=wss://api.growagarden.com/socket
      - RECONNECT_DELAY=5
      - MAX_RECONNECT_ATTEMPTS=10
      
      # Update intervals
      - UPDATE_INTERVAL=300
      - FULL_UPDATE_INTERVAL=300
      
      # Timezone
      - TIMEZONE=Europe/Moscow
      
      # Logging
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/roblox_garden.log
      
      # Use secrets
      - TELEGRAM_BOT_TOKEN_FILE=/run/secrets/telegram_bot_token
      - UPDATES_CHANNEL_ID_FILE=/run/secrets/updates_channel_id
      - FULL_CHANNEL_ID_FILE=/run/secrets/full_channel_id
    
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    
    # Enhanced health check
    healthcheck:
      test: ["CMD", "/app/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Production logging
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    
    # Network configuration
    networks:
      - roblox-garden-net

  # Optional: Monitoring with Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: roblox-garden-prometheus
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   networks:
  #     - roblox-garden-net

  # Optional: Log aggregation with Loki
  # loki:
  #   image: grafana/loki:latest
  #   container_name: roblox-garden-loki
  #   restart: unless-stopped
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ./monitoring/loki.yml:/etc/loki/local-config.yaml
  #     - loki_data:/tmp/loki
  #   networks:
  #     - roblox-garden-net

# Docker secrets (create these files with restricted permissions)
secrets:
  telegram_bot_token:
    file: ./secrets/telegram_bot_token.txt
  updates_channel_id:
    file: ./secrets/updates_channel_id.txt
  full_channel_id:
    file: ./secrets/full_channel_id.txt

# Networks
networks:
  roblox-garden-net:
    driver: bridge

# Volumes for persistence
volumes:
  prometheus_data:
  loki_data:
